language: java
jdk:
  - openjdk8

branches:
  only:
    - main

#빌드 전 권한 추가
before_install:
  - chmod +x gradlew

#Travis Ci 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-prc-webservice *
  - mkdir -p deploy
  - mv springboot-prc-webservice.zip deploy/springboot-prc-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-prc-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-prc-build
    key: springboot-prc-webservice
    build_type: zip
    deployment_group: springboot-prc-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 7273322@naver.com
